# Generated by Django 4.0.5 on 2022-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_author_email_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='bodytext',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
