# Generated by Django 4.0.5 on 2022-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
